import './style.css'
import './mobile.css'
import './theme.css'

const KEY='seok-sdr-rules-v2',now=new Date(),currentMonth=now.toISOString().slice(0,7)
let overviewTitleTimer,paymentCountdownTimer
const defaultBands=[[6,1,12,2],[8,1.5,16,3],[10,2,20,4],[12,2.5,24,5]]
const defaults={settings:{name:'',startDate:'',salary:1500,tax:12,guarantee:500,bands:defaultBands,meetingsByMonth:{}},contracts:[]}
let db=hydrate(JSON.parse(localStorage.getItem(KEY)||'null')),tab='overview',edit={}
const $=s=>document.querySelector(s),uid=()=>crypto.randomUUID(),save=()=>localStorage.setItem(KEY,JSON.stringify(db))
const brl=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),pct=n=>Number(n||0).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%'
const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))
const monthName=m=>new Date(m+'-02T12:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'}),dateBR=d=>d?new Date(d+'T12:00').toLocaleDateString('pt-BR'):'—'
const nextMonth=m=>{let d=new Date(m+'-01T12:00');d.setMonth(d.getMonth()+1);return d.toISOString().slice(0,7)}
const paymentDate=m=>new Date(+m.slice(0,4),+m.slice(5,7)-1,20).toLocaleDateString('pt-BR',{day:'2-digit',month:'long',year:'numeric'})
function saoPauloParts(date=new Date()){return Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date).filter(p=>p.type!=='literal').map(p=>[p.type,+p.value]))}
function nextPaymentAt(date=new Date()){let {year,month,day}=saoPauloParts(date);if(day>20){month++;if(month===13){month=1;year++}}return new Date(Date.UTC(year,month-1,20,3,0,0))}
function nextPaymentLabel(){return new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'numeric',month:'long',year:'numeric'}).format(nextPaymentAt())}
function countdownMarkup(){let target=nextPaymentAt(),today=saoPauloParts(),paymentDay=saoPauloParts(target);if(today.year===paymentDay.year&&today.month===paymentDay.month&&today.day===paymentDay.day)return'<span>Pagamento disponível hoje</span>';let seconds=Math.max(0,Math.floor((target-Date.now())/1000)),days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60),rest=seconds%60,clock=`${String(hours).padStart(2,'0')}h ${String(minutes).padStart(2,'0')}m ${String(rest).padStart(2,'0')}s`;return`<span>Faltam <b>${days} dias</b> <i>${clock}</i></span>`}
function updatePaymentCountdown(){document.querySelectorAll('[data-payment-date]').forEach(el=>el.textContent=nextPaymentLabel());document.querySelectorAll('[data-payment-countdown]').forEach(el=>el.innerHTML=countdownMarkup())}
function startOverviewTimers(){clearInterval(paymentCountdownTimer);clearInterval(overviewTitleTimer);updatePaymentCountdown();paymentCountdownTimer=setInterval(updatePaymentCountdown,1000);let title=$('#overview-title');if(!title||matchMedia('(prefers-reduced-motion: reduce)').matches)return;let alternate=false,name=(db.settings.name||'').trim(),alternateText=name?`Bora vender, ${name}`:'Bora vender';overviewTitleTimer=setInterval(()=>{title.classList.add('is-changing');setTimeout(()=>{if(!title.isConnected)return;alternate=!alternate;title.textContent=alternate?alternateText:'Visão financeira';title.classList.remove('is-changing')},160)},4000)}
function hydrate(saved){let data={...defaults,...(saved||{})},settings={...defaults.settings,...(saved?.settings||{})};settings.bands=settings.bands?.length===4?settings.bands:defaultBands;settings.meetingsByMonth=settings.meetingsByMonth||{};data.settings=settings;data.contracts=Array.isArray(data.contracts)?data.contracts:[];return data}
function meetings(m){return Math.max(0,+db.settings.meetingsByMonth?.[m]||0)}
function tier(count,origin){let i=count<=15?0:count<=19?1:count<=24?2:3,b=db.settings.bands||defaultBands,p=origin==='Outbound'?[b[i][2],b[i][3]]:[b[i][0],b[i][1]];return{initial:+p[0],recurring:+p[1],label:['Até 15 reuniões','16 a 19 reuniões','20 a 24 reuniões','25 ou mais'][i]}}
function contractCalc(c){let locked=Number(c.meetingsAtSigning??meetings(c.signedDate?.slice(0,7))),rates=c.commissionTier||tier(locked,c.origin),base=Number(c.netBase??(+c.gross*(1-Number(db.settings.tax||0)/100))),initialRate=c.initialRate??rates.initial,recurringRate=c.recurringRate??rates.recurring,isNew=c.isNew!=='Não',eligible=isNew&&c.status!=='Perdido'&&!(c.status==='Cancelado'&&c.firstPaid!=='Sim');return{locked,rates,base,initial:base*initialRate/100,recurring:base*recurringRate/100,eligible,initialRate,recurringRate}}
function inGuarantee(m){if(!db.settings.startDate)return false;let s=new Date(db.settings.startDate+'T12:00'),x=new Date(m+'-01T12:00');return x>=new Date(s.getFullYear(),s.getMonth(),1)&&x<new Date(s.getFullYear(),s.getMonth()+2,1)}
function commissionForMonth(m){let confirmedInitial=0,predictedInitial=0,confirmedRecurring=0,predictedRecurring=0,items=[];db.contracts.forEach(c=>{let calc=contractCalc(c);if(!calc.eligible)return;let payments=c.recurringPayments||[],firstPaidMonth=c.firstPaymentDate?.slice(0,7),recurringCount=firstPaidMonth?payments.filter(p=>{let paidMonth=p.date?.slice(0,7);return paidMonth>firstPaidMonth&&nextMonth(paidMonth)===m}).length:0,initialConfirmed=c.firstPaid==='Sim'&&firstPaidMonth&&nextMonth(firstPaidMonth)===m,initialPredicted=c.status==='Assinado'&&c.firstPaid!=='Sim'&&nextMonth(c.signedDate?.slice(0,7))===m,recurringPredicted=c.status!=='Cancelado'&&c.firstPaid==='Sim'&&c.active==='Sim'&&!recurringCount&&firstPaidMonth&&nextMonth(firstPaidMonth)<m;if(initialConfirmed)confirmedInitial+=calc.initial;if(initialPredicted)predictedInitial+=calc.initial;confirmedRecurring+=recurringCount*calc.recurring;if(recurringPredicted)predictedRecurring+=calc.recurring;if(initialConfirmed||initialPredicted||recurringCount||recurringPredicted)items.push({c,calc,initialConfirmed,initialPredicted,recurringConfirmed:recurringCount*calc.recurring,recurringPredicted})});return{confirmedInitial,predictedInitial,confirmedRecurring,predictedRecurring,items}}
function remuneration(m){let c=commissionForMonth(m),confirmed=c.confirmedInitial+c.confirmedRecurring,minimum=inGuarantee(m)?Math.max(0,+db.settings.guarantee-confirmed):0,guaranteed=+db.settings.salary+confirmed+minimum,confirmation=c.predictedInitial+c.predictedRecurring;return{...c,confirmed,minimum,guaranteed,confirmation,projected:guaranteed+confirmation,guaranteeActive:inGuarantee(m)}}
function monthInput(id='period',m=currentMonth){return`<label class="period">Mês de recebimento <input id="${id}" type="month" value="${m}"></label>`}
function goalPanel(m){let count=meetings(m),inbound=tier(count,'Inbound'),outbound=tier(count,'Outbound');return`<section class="panel goal-panel"><div><p class="section-label">Meta de comissão</p><h2>${count} <small>/ 20 reuniões validadas</small></h2><div class="goalbar"><i><em style="width:${Math.min(100,count/20*100)}%"></em></i><span>${pct(count/20*100)} de atingimento</span></div><p>A quantidade de reuniões validadas no mês da assinatura trava a faixa daquele contrato.</p></div><form id="meetings-form"><label>Reuniões validadas em ${monthName(m)}<input name="meetings" min="0" type="number" value="${count}"></label><button class="secondary">Atualizar meta</button></form><div class="tier-summary"><span>Inbound <b>${inbound.initial}% inicial · ${inbound.recurring}% recorrente</b></span><span>Outbound <b>${outbound.initial}% inicial · ${outbound.recurring}% recorrente</b></span></div></section>`}
function financeCards(r){return`<section class="finance-grid"><article class="pay-card"><p>Próximo pagamento</p><h2>${brl(r.guaranteed)}</h2><small>Valor garantido</small></article><article><span>Em confirmação</span><b>${brl(r.confirmation)}</b><small>depende de pagamento confirmado</small></article><article><span>Projeção total</span><b>${brl(r.projected)}</b><small>Garantido + em confirmação</small></article></section><section class="commission-grid"><article><span>Salário fixo</span><b>${brl(db.settings.salary)}</b></article><article><span>Inicial confirmada</span><b>${brl(r.confirmedInitial)}</b></article><article><span>Recorrente confirmada</span><b>${brl(r.confirmedRecurring)}</b></article><article><span>Garantia mínima</span><b>${brl(r.minimum)}</b><small>${r.guaranteeActive?'ativa nos dois primeiros meses':'não se aplica'}</small></article></section>`}
function financialTrend(months){let points=months.map((month,index)=>({month,index,value:remuneration(month).projected})).filter(p=>Number.isFinite(p.value));if(!points.length)return`<p class="trend-empty">Registre contratos para acompanhar sua evolução financeira.</p>`;let values=points.map(p=>p.value),min=Math.min(...values),max=Math.max(...values),range=Math.max(max-min,max*.12,1),floor=Math.max(0,min-range*.12),ceiling=max+range*.12,plotHeight=154,left=68,right=694,base=194,top=34,coords=points.map(p=>({...p,x:left+p.index*(right-left)/Math.max(1,points.length-1),y:base-(p.value-floor)/(ceiling-floor)*(base-top)})),line=coords.map((p,i)=>`${i?'L':'M'} ${p.x.toFixed(1)} ${p.y.toFixed(1)}`).join(' '),area=`${line} L ${coords.at(-1).x.toFixed(1)} ${base} L ${coords[0].x.toFixed(1)} ${base} Z`,active=coords.at(-1),label=v=>`R$ ${(v/1000).toLocaleString('pt-BR',{maximumFractionDigits:1})}k`,grid=[top,top+plotHeight/2,base].map((y,i)=>({y,value:ceiling-(ceiling-floor)*i/2}));return`<figure class="finance-trend"><figcaption><span class="trend-key"></span>Total projetado mensal</figcaption><div class="trend-plot"><svg viewBox="0 0 720 224" preserveAspectRatio="none" role="img" aria-label="Evolução do total projetado mensal nos últimos seis meses"><defs><linearGradient id="trend-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#A8FF3E" stop-opacity=".28"/><stop offset="100%" stop-color="#A8FF3E" stop-opacity="0"/></linearGradient><radialGradient id="trend-glow"><stop stop-color="#A8FF3E" stop-opacity=".32"/><stop offset="1" stop-color="#A8FF3E" stop-opacity="0"/></radialGradient></defs>${grid.map(g=>`<g><line class="trend-grid" x1="${left}" y1="${g.y.toFixed(1)}" x2="${right}" y2="${g.y.toFixed(1)}"/><text class="trend-axis" x="0" y="${(g.y+4).toFixed(1)}">${label(g.value)}</text></g>`).join('')}<circle class="trend-halo" cx="${active.x.toFixed(1)}" cy="${active.y.toFixed(1)}" r="76"/><line class="trend-focus" x1="${active.x.toFixed(1)}" y1="${top}" x2="${active.x.toFixed(1)}" y2="${base}"/><line class="trend-focus-level" x1="${left}" y1="${active.y.toFixed(1)}" x2="${right}" y2="${active.y.toFixed(1)}"/><path class="trend-area" d="${area}"/><path class="trend-line" d="${line}"/></svg>${coords.map((p,i)=>`<button class="trend-point" type="button" style="left:${(p.x/720*100).toFixed(2)}%;top:${(p.y/224*100).toFixed(2)}%" aria-label="${esc(monthName(p.month))}: ${brl(p.value)}" data-edge="${i===0?'first':i===coords.length-1?'last':''}" data-active="${i===coords.length-1?'true':'false'}" data-tooltip-position="${p.y<74?'below':'above'}"><span class="trend-tooltip"><small>Total projetado</small>${esc(monthName(p.month))}<strong>${brl(p.value)}</strong></span></button>`).join('')}</div><div class="trend-months">${months.map(month=>`<span>${esc(new Date(month+'-02T12:00').toLocaleDateString('pt-BR',{month:'short'}))}</span>`).join('')}</div></figure>`}
function monthsBetween(start,end){let months=[],cursor=new Date(start+'-01T12:00'),limit=new Date(end+'-01T12:00');while(cursor<=limit){months.push(cursor.toISOString().slice(0,7));cursor.setMonth(cursor.getMonth()+1)}return months}
function financialHistory(m,start='',end=''){let firstMonth=db.settings.startDate?.slice(0,7)||m,defaultEnd=nextMonth(m),rangeStart=start&&start>=firstMonth?start:firstMonth,rangeEnd=end&&end>=rangeStart?end:defaultEnd;if(rangeEnd<rangeStart)rangeEnd=rangeStart;let months=monthsBetween(rangeStart,rangeEnd);return`<section id="financial-history" class="panel history"><header><div><p class="section-label">Histórico real</p><h2>Evolução financeira mensal</h2><p>Somente valores a partir do início do seu contrato.</p></div><div class="trend-filters"><label>De<input id="trend-start" type="month" min="${firstMonth}" max="${rangeEnd}" value="${rangeStart}"></label><label>Até<input id="trend-end" type="month" min="${rangeStart}" value="${rangeEnd}"></label></div></header>${financialTrend(months)}<div class="table"><table><thead><tr><th>Mês</th><th>Salário</th><th>Inicial</th><th>Recorrência</th><th>Garantido</th><th>Projetado</th></tr></thead><tbody>${months.map(month=>{let r=remuneration(month);return`<tr><td>${monthName(month)}</td><td>${brl(db.settings.salary)}</td><td>${brl(r.confirmedInitial)}</td><td>${brl(r.confirmedRecurring)}</td><td><b>${brl(r.guaranteed)}</b></td><td>${brl(r.projected)}</td></tr>`}).join('')}</tbody></table></div></section>`}
function overview(){let m=currentMonth;return`<header class="head finance-head"><div><h1 id="overview-title" class="overview-title" aria-live="polite">Visão financeira</h1></div>${monthInput()}</header><div id="financial-data">${overviewData(m)}</div>`}
function paymentCountdownStrip(){return`<section class="payment-countdown-bar"><span><b>Próximo pagamento</b><i data-payment-date>${nextPaymentLabel()}</i></span><output class="payment-countdown" data-payment-countdown aria-live="polite">${countdownMarkup()}</output></section>`}
function overviewData(m){let r=remuneration(m);return`${paymentCountdownStrip()}${financeCards(r)}${receiptItemsPanel(m,r)}${goalPanel(m)}${financialHistory(m)}`}
function choice(name,label,value){return`<label>${label}<select name="${name}"><option ${value==='Não'?'selected':''}>Não</option><option ${value==='Sim'?'selected':''}>Sim</option></select></label>`}
function contractForm(){let c=edit.contract||{};return`<section class="panel form"><header><div><p class="section-label">Contrato financeiro</p><h2>${c.id?'Editar contrato':'Novo contrato'}</h2><p>A faixa é travada ao salvar, usando as reuniões do mês da assinatura.</p></div></header><form id="contract-form"><input type="hidden" name="id" value="${c.id||''}"><label>Empresa ou cliente<input required name="company" value="${esc(c.company)}"></label><div class="form-grid"><label>Origem<select name="origin"><option ${c.origin==='Inbound'?'selected':''}>Inbound</option><option ${c.origin==='Outbound'?'selected':''}>Outbound</option></select></label><label>Data da assinatura<input required name="signedDate" type="date" value="${c.signedDate||now.toISOString().slice(0,10)}"></label></div>${choice('isNew','Contrato novo',c.isNew??'Sim')}<label>Valor mensal bruto do contrato<input required min="0" step=".01" name="gross" type="number" value="${c.gross??''}"></label><div class="form-grid">${choice('firstPaid','Primeira fatura paga',c.firstPaid)}<label>Data da primeira fatura<input name="firstPaymentDate" type="date" value="${c.firstPaymentDate||''}"></label></div><div class="form-grid">${choice('active','Cliente ativo',c.active)}<label>Status<select name="status"><option ${c.status==='Em negociação'?'selected':''}>Em negociação</option><option ${c.status==='Assinado'||!c.status?'selected':''}>Assinado</option><option ${c.status==='Pago'?'selected':''}>Pago</option><option ${c.status==='Cancelado'?'selected':''}>Cancelado</option><option ${c.status==='Perdido'?'selected':''}>Perdido</option></select></label></div><label>Observação<textarea name="note">${esc(c.note)}</textarea></label><button class="primary">${c.id?'Salvar alterações':'Salvar contrato'}</button></form></section>`}
function receiptText(c){if(c.firstPaid==='Sim'&&c.firstPaymentDate)return`Próximo inicial: ${paymentDate(nextMonth(c.firstPaymentDate.slice(0,7)))}`;if(c.status==='Assinado')return`Previsão inicial: ${paymentDate(nextMonth(c.signedDate.slice(0,7)))}`;return'Contrato sem recebimento elegível'}
function contractTable(){let rows=[...db.contracts].sort((a,b)=>(b.signedDate||'').localeCompare(a.signedDate||'')),month=currentMonth;return`<section class="panel contracts"><header><div><p class="section-label">Histórico financeiro</p><h2>Contratos e comissões</h2><p>Base líquida = bruto menos ${db.settings.tax}% de impostos.</p></div></header><div class="table"><table><thead><tr><th>Contrato</th><th>Faixa travada</th><th>Base líquida</th><th>Comissão</th><th>Recebimento</th><th></th></tr></thead><tbody>${rows.length?rows.map(c=>{let x=contractCalc(c),firstPaidMonth=c.firstPaymentDate?.slice(0,7),validRecurring=firstPaidMonth?(c.recurringPayments||[]).filter(p=>p.date?.slice(0,7)>firstPaidMonth):[],confirmed=(c.firstPaid==='Sim'&&firstPaidMonth?x.initial:0)+validRecurring.length*x.recurring,predicted=x.eligible&&(c.status==='Assinado'&&c.firstPaid!=='Sim'?x.initial:c.status!=='Cancelado'&&c.firstPaid==='Sim'&&c.active==='Sim'?x.recurring:0),confirmedThisMonth=validRecurring.some(p=>p.date?.slice(0,7)===month),canConfirm=c.status!=='Cancelado'&&c.firstPaid==='Sim'&&c.active==='Sim'&&x.eligible&&firstPaidMonth&&month>firstPaidMonth;return`<tr><td><b>${esc(c.company)}</b><small>${c.origin} · assinado em ${dateBR(c.signedDate)}</small></td><td>${c.origin} ${x.initialRate}% inicial / ${x.recurringRate}% recorrente</td><td>${brl(x.base)}</td><td><b>${brl(confirmed)}</b><small>Prevista: ${brl(predicted)}</small></td><td>${receiptText(c)}</td><td>${canConfirm?`<button class="confirm-recurring" data-id="${c.id}" ${confirmedThisMonth?'disabled':''}>${confirmedThisMonth?'Mensalidade confirmada':'Confirmar mensalidade'}</button>`:''}<button class="edit" data-id="${c.id}">Editar</button><button class="delete" data-id="${c.id}" aria-label="Excluir ${esc(c.company)}">×</button></td></tr>`}).join(''):`<tr><td colspan="6">Nenhum contrato cadastrado. Registre um contrato para iniciar sua projeção.</td></tr>`}</tbody></table></div></section>`}
function contracts(){return`<header class="head"><div><p class="section-label">Comissão contratual</p><h1>Contratos e comissões</h1><p>Registre apenas fatos que alteram seu recebimento.</p></div></header><div class="contract-layout">${contractForm()}${contractTable()}</div>`}
function receiptItemsPanel(m,r){return`<section class="panel projection-panel"><header><div><p class="section-label">Itens do recebimento</p><h2>Recebimento em ${paymentDate(m)}</h2></div></header><div class="projection-list">${r.items.length?r.items.map(i=>`<div><span><b>${esc(i.c.company)}</b><small>${i.initialConfirmed?'Inicial confirmada':i.initialPredicted?'Inicial em confirmação':i.recurringConfirmed?'Recorrência confirmada':'Recorrência prevista'}</small></span><b>${brl((i.initialConfirmed?i.calc.initial:0)+(i.initialPredicted?i.calc.initial:0)+i.recurringConfirmed+(i.recurringPredicted?i.calc.recurring:0))}</b></div>`).join(''):'<p>Nenhum recebimento cadastrado para este mês.</p>'}</div></section>`}
function settings(){let s=db.settings,b=s.bands;return`<header class="head"><div><p class="section-label">Regras do contrato</p><h1>Configurações</h1><p>Esses parâmetros explicam seus valores de comissão.</p></div></header><section class="panel form settings"><form id="settings-form"><label>Nome do SDR<input name="name" value="${esc(s.name)}"></label><div class="form-grid"><label>Início do contrato<input name="startDate" type="date" value="${s.startDate||''}"></label><label>Salário fixo mensal<input min="0" step=".01" name="salary" type="number" value="${s.salary}"></label></div><div class="form-grid"><label>Impostos (%)<input min="0" max="100" step=".01" name="tax" type="number" value="${s.tax}"></label><label>Garantia mínima de comissão<input min="0" step=".01" name="guarantee" type="number" value="${s.guarantee}"></label></div><section class="bands"><header><div><p class="section-label">Faixas de comissão</p><h2>Percentuais por reuniões validadas</h2></div></header>${['Até 15 reuniões','16 a 19 reuniões','20 a 24 reuniões','25 ou mais'].map((label,i)=>`<fieldset><legend>${label}</legend><label>Inbound inicial<input name="i${i}" step=".1" type="number" value="${b[i][0]}"></label><label>Inbound recorrente<input name="r${i}" step=".1" type="number" value="${b[i][1]}"></label><label>Outbound inicial<input name="o${i}" step=".1" type="number" value="${b[i][2]}"></label><label>Outbound recorrente<input name="or${i}" step=".1" type="number" value="${b[i][3]}"></label></fieldset>`).join('')}</section><button class="primary">Salvar configurações</button></form></section><section class="panel backup"><h2>Backup financeiro</h2><p>Exporte seus contratos e configurações ou importe um backup JSON.</p><div><button data-export="csv" class="secondary">Exportar CSV</button><button data-export="json" class="secondary">Baixar backup JSON</button><label class="secondary">Importar JSON<input id="import" type="file" accept="application/json" hidden></label></div></section>`}
const pages={overview,contracts,settings}
function render(){if(!pages[tab])tab='overview';let initials=(db.settings.name||'SD').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();$('#app').innerHTML=`<aside><a class="brand"><b>seok</b><i>finance</i></a><nav>${[['overview','▣','Visão financeira'],['contracts','R$','Contratos e comissões'],['settings','⚙','Configurações']].map(x=>`<button class="${tab===x[0]?'active':''}" data-tab="${x[0]}"><span>${x[1]}</span>${x[2]}</button>`).join('')}</nav><footer><i>${initials}</i><p><b>${esc(db.settings.name||'SDR')}</b><small>Comissão e recebimento</small></p></footer></aside><main><header class="mobile"><button id="menu" aria-label="Abrir menu">☰</button><a class="brand"><b>seok</b><i>finance</i></a><button data-tab="settings" aria-label="Configurações">⚙</button></header><div class="content">${pages[tab]()}</div></main><div id="toast"></div>`;bind()}
function refreshFinancialHistory(){let start=$('#trend-start')?.value,end=$('#trend-end')?.value,reference=$('#period')?.value||currentMonth;if(!start||!end)return;if(end<start){end=start;$('#trend-end').value=end}let current=$('#financial-history');if(!current)return;current.outerHTML=financialHistory(reference,start,end);bindFinancialHistoryFilters()}
function bindFinancialHistoryFilters(){$('#trend-start')?.addEventListener('change',refreshFinancialHistory);$('#trend-end')?.addEventListener('change',refreshFinancialHistory)}
function bind(){clearInterval(paymentCountdownTimer);clearInterval(overviewTitleTimer);if(tab==='overview')startOverviewTimers();document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;edit={};render()});$('#menu')?.addEventListener('click',()=>$('aside').classList.toggle('open'));$('#period')?.addEventListener('change',e=>{$('#financial-data').innerHTML=overviewData(e.target.value);bindFinancialHistoryFilters()});bindFinancialHistoryFilters();$('#meetings-form')?.addEventListener('submit',saveMeetings);$('#contract-form')?.addEventListener('submit',saveContract);$('#settings-form')?.addEventListener('submit',saveSettings);document.querySelectorAll('.confirm-recurring').forEach(b=>b.onclick=()=>confirmRecurring(b.dataset.id));document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>{edit.contract=structuredClone(db.contracts.find(c=>c.id===b.dataset.id));render()});document.querySelectorAll('.delete').forEach(b=>b.onclick=()=>{db.contracts=db.contracts.filter(c=>c.id!==b.dataset.id);save();render();toast('Contrato excluído')});$('[data-export="csv"]')?.addEventListener('click',exportCSV);$('[data-export="json"]')?.addEventListener('click',()=>download(JSON.stringify(db,null,2),'backup-financeiro-seok.json','application/json'));$('#import')?.addEventListener('change',importJSON)}
function saveMeetings(e){e.preventDefault();let m=$('#period')?.value||currentMonth;db.settings.meetingsByMonth[m]=Math.max(0,+new FormData(e.target).get('meetings')||0);save();$('#financial-data').innerHTML=overviewData(m);bind();toast('Meta de comissão atualizada')}
function saveContract(e){e.preventDefault();let x=Object.fromEntries(new FormData(e.target)),old=edit.contract;if(x.firstPaid==='Sim'&&!x.firstPaymentDate){alert('Informe a data da primeira fatura paga.');return}let meetingsAtSigning=meetings(x.signedDate.slice(0,7)),rates=tier(meetingsAtSigning,x.origin),base=+x.gross*(1-Number(db.settings.tax||0)/100),recurringPayments=old?.recurringPayments||[];Object.assign(x,{gross:+x.gross,meetingsAtSigning,commissionTier:rates,initialRate:rates.initial,recurringRate:rates.recurring,netBase:base,recurringPayments});if(x.id){let i=db.contracts.findIndex(c=>c.id===x.id);db.contracts[i]={...db.contracts[i],...x};delete edit.contract}else{delete x.id;db.contracts.push({...x,id:uid()})}save();render();toast('Contrato salvo')}
function confirmRecurring(id){let contract=db.contracts.find(c=>c.id===id),month=currentMonth,firstPaidMonth=contract?.firstPaymentDate?.slice(0,7);if(!contract||contract.status==='Cancelado'||contract.firstPaid!=='Sim'||contract.active!=='Sim'||!contractCalc(contract).eligible)return;if(!firstPaidMonth||month<=firstPaidMonth){toast('A recorrência só é devida a partir da segunda fatura paga');return}let payments=contract.recurringPayments||[];if(payments.some(p=>p.date?.slice(0,7)===month)){toast('Mensalidade já confirmada neste mês');return}contract.recurringPayments=[...payments,{id:uid(),date:`${month}-01`}];save();render();toast('Mensalidade confirmada')}
function saveSettings(e){e.preventDefault();let x=Object.fromEntries(new FormData(e.target)),bands=defaultBands.map((_,i)=>[+x[`i${i}`],+x[`r${i}`],+x[`o${i}`],+x[`or${i}`]]);db.settings={...db.settings,name:x.name,startDate:x.startDate,salary:+x.salary,tax:+x.tax,guarantee:+x.guarantee,bands};save();render();toast('Configurações salvas')}
function exportCSV(){let rows=[['empresa','origem','assinatura','base_liquida','faixa_reunioes','inicial_pct','recorrente_pct','confirmada','prevista','proximo_recebimento'],...db.contracts.map(c=>{let x=contractCalc(c),firstPaidMonth=c.firstPaymentDate?.slice(0,7),validRecurring=firstPaidMonth?(c.recurringPayments||[]).filter(p=>p.date?.slice(0,7)>firstPaidMonth):[],confirmed=(c.firstPaid==='Sim'&&firstPaidMonth?x.initial:0)+validRecurring.length*x.recurring,predicted=x.eligible?(c.firstPaid==='Sim'&&c.active==='Sim'?x.recurring:(c.status==='Assinado'?x.initial:0)):0;return[c.company,c.origin,c.signedDate,x.base,x.locked,x.initialRate,x.recurringRate,confirmed,predicted,receiptText(c)]})];download('\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n'),'comissoes-seok.csv','text/csv;charset=utf-8')}
function importJSON(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=hydrate(JSON.parse(r.result));save();render();toast('Backup financeiro importado')}catch{alert('Arquivo JSON de backup inválido.')}};r.readAsText(f)}
function download(content,name,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function toast(text){let n=$('#toast');n.textContent=text;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2200)}
document.addEventListener('click',e=>{let aside=$('aside'),menu=e.target.closest('#menu'),tabButton=e.target.closest('[data-tab]');if(menu)setTimeout(()=>document.body.classList.toggle('menu-open',!!aside?.classList.contains('open')));if(tabButton){aside?.classList.remove('open');document.body.classList.remove('menu-open')}if(document.body.classList.contains('menu-open')&&!menu&&!tabButton&&!e.target.closest('aside')){aside?.classList.remove('open');document.body.classList.remove('menu-open')}})
render()
